=== Geontech/sca-jtnc/xml/dtd/softwarecomponent.dtd
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!ELEMENT softwarecomponent
	( corbaversion
	, componentrepid
	, componenttype
	, componentfeatures
	, interfaces
	, propertyfile?
	)>

<!ELEMENT propertyfile
	(localfile
	)>
<!ATTLIST propertyfile
	type		CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT corbaversion (#PCDATA)> 

<!ELEMENT componentrepid EMPTY>
<!ATTLIST componentrepid
	repid		CDATA	#REQUIRED>

<!ELEMENT componenttype (#PCDATA)>

<!ELEMENT componentfeatures
	( supportsinterface* 
	, ports
	)>

<!ELEMENT supportsinterface EMPTY>
<!ATTLIST supportsinterface
	repid			CDATA	#REQUIRED
 	supportsname	CDATA	#REQUIRED>

<!ELEMENT ports
	(provides   
	| uses
	)*> 

<!ELEMENT provides
	( description?
	, porttype* 
        )>
<!ATTLIST provides
	repid			CDATA	#REQUIRED
	providesname	CDATA	#REQUIRED>

<!ELEMENT uses
	( description?
	, porttype*
        )>
<!ATTLIST uses
	repid		CDATA	#REQUIRED
	usesname	CDATA	#REQUIRED>

<!ELEMENT description (#PCDATA)>
<!ELEMENT porttype EMPTY>
<!ATTLIST porttype
    	type	( data | control | responses	| test | virtual ) 	#REQUIRED>

<!ELEMENT interfaces
	( interface+ 
	)>

<!ELEMENT interface
	( inheritsinterface*)>
<!ATTLIST interface
	repid		CDATA	#REQUIRED
	name		CDATA	#REQUIRED>

<!ELEMENT inheritsinterface EMPTY>
<!ATTLIST inheritsinterface
	repid		CDATA	#REQUIRED>

=== Geontech/sca-jtnc/control/sdr/devmgr/DeviceManager.scd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwarecomponent PUBLIC "-//JTRS//DTD SCA V2.2.2 SCD//EN" "softwarecomponent.dtd">
<softwarecomponent>
	<corbaversion>2.2</corbaversion>
	<componentrepid repid="IDL:CF/DeviceManager:1.0"/>
	<componenttype>devicemanager</componenttype>
	<componentfeatures>
		<supportsinterface repid="IDL:CF/DeviceManager:1.0" supportsname="DeviceManager"/>
		<supportsinterface repid="IDL:CF/PropertySet:1.0" supportsname="PropertySet"/>
                <ports/>
	</componentfeatures>
	<interfaces>
		<interface repid="IDL:CF/DeviceManager:1.0" name="DeviceManager">
			<inheritsinterface repid="IDL:CF/PropertySet:1.0"/>
		</interface>
		<interface repid="IDL:CF/PropertySet:1.0" name="PropertySet"/>
	</interfaces>
</softwarecomponent>

=== Geontech/sca-jtnc/testing/sdr/dev/devices/BasicUsesDevice/BasicUsesDevice.scd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!--
This file is protected by Copyright. Please refer to the COPYRIGHT file 
distributed with this source distribution.

This file is part of REDHAWK core.

REDHAWK core is free software: you can redistribute it and/or modify it under 
the terms of the GNU Lesser General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

REDHAWK core is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR 
A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more 
details.

You should have received a copy of the GNU Lesser General Public License along 
with this program.  If not, see http://www.gnu.org/licenses/.
-->

<!DOCTYPE softwarecomponent PUBLIC '-//JTRS//DTD SCA V2.2.2 SCD//EN' 'softwarecomponent.dtd'>
<softwarecomponent>
    <corbaversion>2.2</corbaversion>
    <componentrepid repid="IDL:CF/Device:1.0" />
    <componenttype>device</componenttype>
    <componentfeatures>
        <supportsinterface repid="IDL:CF/Device:1.0" supportsname="Device" />
        <supportsinterface repid="IDL:CF/Resource:1.0" supportsname="Resource" />
        <supportsinterface repid="IDL:CF/PortSupplier:1.0" supportsname="PortSupplier" />
        <supportsinterface repid="IDL:CF/PropertySet:1.0" supportsname="PropertySet" />
        <supportsinterface repid="IDL:CF/TestableObject:1.0" supportsname="TestableObject" />
        <supportsinterface repid="IDL:CF/LifeCycle:1.0" supportsname="LifeCycle" />
        <ports>
            <provides providesname="resource_in" repid="IDL:CF/Resource:1.0">
                <porttype type="test"/>
            </provides>
        </ports>
    </componentfeatures>
    <interfaces>
        <interface repid="IDL:CF/Device:1.0" name="BasicUsesDevice">
            <!--[Inherited interface IDL:CF/Resource:1.0]-->
            <inheritsinterface repid="IDL:CF/Resource:1.0" />
            <!--[Inherited interface IDL:CF/PortSupplier:1.0]-->
            <inheritsinterface repid="IDL:CF/PortSupplier:1.0" />
            <!--[Inherited interface IDL:CF/PropertySet:1.0]-->
            <inheritsinterface repid="IDL:CF/PropertySet:1.0" />
            <!--[Inherited interface IDL:CF/TestableObject:1.0]-->
            <inheritsinterface repid="IDL:CF/TestableObject:1.0" />
            <!--[Inherited interface IDL:CF/LifeCycle:1.0]-->
            <inheritsinterface repid="IDL:CF/LifeCycle:1.0" />
        </interface>
    </interfaces>
</softwarecomponent>

=== Geontech/sca-jtnc/base/codegen/sca/packagegen/templates/resourceTemplate.scd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarecomponent PUBLIC "-//JTRS//DTD SCA V2.2.2 SCD//EN" "softwarecomponent.dtd">
<softwarecomponent>
    <corbaversion>2.2</corbaversion>
    <componentrepid repid="IDL:CF/Resource:1.0"/>
    <componenttype>resource</componenttype>
    <componentfeatures>
        <supportsinterface supportsname="Resource" repid="IDL:CF/Resource:1.0"/>
        <supportsinterface supportsname="LifeCycle" repid="IDL:CF/LifeCycle:1.0"/>
        <supportsinterface supportsname="PortSupplier" repid="IDL:CF/PortSupplier:1.0"/>
        <supportsinterface supportsname="PropertySet" repid="IDL:CF/PropertySet:1.0"/>
        <supportsinterface supportsname="IDL:CF/TestableObject:1.0" repid="TestableObject"/>
        <ports/>
    </componentfeatures>
    <interfaces>
        <interface name="Resource" repid="IDL:CF/Resource:1.0">
            <inheritsinterface repid="IDL:CF/LifeCycle:1.0"/>
            <inheritsinterface repid="IDL:CF/PortSupplier:1.0"/>
            <inheritsinterface repid="IDL:CF/PropertySet:1.0"/>
            <inheritsinterface repid="IDL:CF/TestableObject:1.0"/>
        </interface>
        <interface name="LifeCycle" repid="IDL:CF/LifeCycle:1.0"/>
        <interface name="PortSupplier" repid="IDL:CF/PortSupplier:1.0"/>
        <interface name="PropertySet" repid="IDL:CF/PropertySet:1.0"/>
        <interface name="TestableObject" repid="IDL:CF/TestableObject:1.0"/>
        <interface name="ProvidesPortStatisticsProvider" repid="IDL:BULKIO/ProvidesPortStatisticsProvider:1.0"/>
        <interface name="updateSRI" repid="IDL:BULKIO/updateSRI:1.0"/>
    </interfaces>
</softwarecomponent>
